_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
active_architecture:
    value: unet3d
active_dataset:
    value: Task04_Hippocampus
architectures:
    value:
        unet3d:
            model_defaults:
                deep_supervision:
                    enabled: true
                    inference_fusion_mode: only_final
                    levels: 3
                depth: 4
                in_channels: 1
                loss:
                    name: CombinedLoss
                    params:
                        alpha: 0.35
                        ignore_index: null
                n_filters: 8
            training_defaults:
                batch_norm: true
                batch_size: 2
                drop_last: true
                dropout: 0.1
                num_epochs: 100
                optimizer:
                    name: AdamW
                    params:
                        lr: 0.0001
                        weight_decay: 1e-07
                patience: 5
                scheduler:
                    _target_: torch.optim.lr_scheduler.StepLR
                    gamma: 0.1
                    step_size: 30
datasets:
    value:
        Task01_BrainTumour:
            base_path: datasets/Task01_BrainTumour/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 4
            overrides:
                model:
                    deep_supervision:
                        enabled: true
                        inference_fusion_mode: weighted_softmax
                        levels: 4
                    depth: 5
                    in_channels: 4
                    loss:
                        name: CombinedLoss
                        params:
                            alpha: 0.3
                            ignore_index: 0
                    n_filters: 16
                training:
                    batch_size: 1
                    num_epochs: 100
                    patience: 15
            target_shape:
                - 256
                - 256
                - 160
        Task02_Heart:
            base_path: datasets/Task02_Heart/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 2
            target_shape:
                - 256
                - 256
                - 128
        Task03_Liver:
            base_path: datasets/Task03_Liver/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 3
            target_shape:
                - 512
                - 512
                - 64
        Task04_Hippocampus:
            base_path: datasets/Task04_Hippocampus/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 3
            overrides:
                model:
                    deep_supervision:
                        enabled: true
                        inference_fusion_mode: weighted_softmax
                        levels: 4
                    depth: 5
                    loss:
                        name: CombinedLoss
                        params:
                            alpha: 0.3
                            ignore_index: 0
                    n_filters: 32
                training:
                    batch_size: 2
                    drop_last: false
                    dropout: 0.3
                    num_epochs: 100
                    patience: 15
            target_shape:
                - 32
                - 64
                - 32
        Task05_Prostate:
            base_path: datasets/Task05_Prostate/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 3
            target_shape:
                - 256
                - 256
                - 32
        Task06_Lung:
            base_path: datasets/Task06_Lung/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 2
            target_shape:
                - 512
                - 512
                - 128
        Task07_Pancreas:
            base_path: datasets/Task07_Pancreas/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 3
            target_shape:
                - 256
                - 256
                - 64
        Task08_HepaticVessel:
            base_path: datasets/Task08_HepaticVessel/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 3
            target_shape:
                - 512
                - 512
                - 128
        Task09_Spleen:
            base_path: datasets/Task09_Spleen/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 2
            target_shape:
                - 512
                - 512
                - 64
        Task10_Colon:
            base_path: datasets/Task10_Colon/
            images_subdir: imagesTr
            labels_subdir: labelsTr
            num_classes: 2
            target_shape:
                - 256
                - 256
                - 128
gpu:
    value:
        backend: nccl
        devices:
            - 3
        mode: single
tracking:
    value:
        log_to_wandb: true
        run_name: unet_run_2025-04-02_02-06-02
        wandb_project: MedicalSegmentation
trained_models:
    value:
        base_dir: trained_models
