# Hardware settings (applies globally)
gpu:
  mode: "single"         # Options: "single", "multi"
  devices: [2]           # e.g., [0, 1, 2, 3] for multi-GPU
  backend: "nccl"        # "nccl" for GPU, "gloo" for CPU

# Active dataset selection
active_architecture: unet
active_dataset: Task04_Hippocampus

# Don't change below, these are default values, change overrides in datasets!
architectures:
  unet:
    model_defaults: # Only configuration for the model
      depth: 4
      n_filters: 8
      deep_supervision:
        enabled: true
        use_all_outputs_during_inference: true #Ask mostafa if we should have seperate so we can enable for train, but disable for validation 
        prediction_fusion_mode: 'weighted_softmax' # 'only_final', 'weighted_softmax', 'weighted_majority'
      loss:
        name: "CombinedLoss"
        params:
          alpha: 0.7
          ignore_index: 0
          eps: 1e-6
    training_defaults: # Only configuration during training
      batch_size: 2
      learning_rate: 1e-3
      weight_decay: 1e-7
      num_epochs: 100
      dropout: 0.1
      drop_last: True
      patience: 5
    validation_defaults: # TODO implement IF AND ONLY IF U HAVE EXTRA TIME  
      batch_size: 2
      eval_metric: 'dice_score' 
  # diffnet:
  #   defaults:
  #     timesteps: 1000
  #     beta_schedule: "linear"
  #     loss:
  #       name: "MSE"
  #   training_defaults:
  #     batch_size: 4
  #     learning_rate: 2e-4
  #     num_epochs: 200


# Dataset configurations
datasets:
  Task01_BrainTumour:
    target_shape: [256, 256, 128]
    base_path: "datasets/Task01_BrainTumour/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 4
    unet_overrides:  
      training:
        batch_size: 1
        learning_rate: 1e-4
      

  Task02_Heart:
    target_shape: [256, 256, 128]
    base_path: "datasets/Task02_Heart/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 2

  Task03_Liver:
    target_shape: [512, 512, 64]
    base_path: "datasets/Task03_Liver/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 3

  Task04_Hippocampus:
    target_shape: [32, 64, 32]
    base_path: "datasets/Task04_Hippocampus/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 3
    unet_overrides:
      training:
        batch_size: 4
        learning_rate: 1e-4
        num_epochs: 60
        dropout: 0.2
        drop_last: False
        patience: 10
      model: 
        n_filters: 32
    
  Task05_Prostate:
    target_shape: [256, 256, 32]
    base_path: "datasets/Task05_Prostate/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 3

  Task06_Lung:
    target_shape: [512, 512, 128]
    base_path: "datasets/Task06_Lung/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 2

  Task07_Pancreas:
    target_shape: [256, 256, 64]
    base_path: "datasets/Task07_Pancreas/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 3

  Task08_HepaticVessel:
    target_shape: [512, 512, 128]
    base_path: "datasets/Task08_HepaticVessel/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 3

  Task09_Spleen:
    target_shape: [512, 512, 64]
    base_path: "datasets/Task09_Spleen/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 2

  Task10_Colon:
    target_shape: [256, 256, 128]
    base_path: "datasets/Task10_Colon/"
    images_subdir: "imagesTr"
    labels_subdir: "labelsTr"
    num_classes: 2

# Model storage
trained_models:
  base_dir: "trained_models"