# Description: Configuration file for the project

gpu:
  mode: "single"  # Options: "single", "multi"
  devices: [1]    # Change this to [0, 1, 2, 3] for multi-GPU 
  backend: "nccl" # Use "gloo" if running on CPU, "nccl" if running on GPU, src: https://pytorch.org/docs/stable/distributed.html

dataset:
  task_name: "Task08_HepaticVessel"
  target_shape: [512, 512, 128]     
  base_path: "datasets/"          
  images_subdir: "imagesTr"
  labels_subdir: "labelsTr"

training:
  batch_size: 2
  learning_rate: 1e-3
  weight_decay: 1e-7
  num_epochs: 1
  n_filters: 8
  dropout: 0.05
  num_classes: 3
  drop_last: True

trained_models: 
  base_dir: "trained_models"
