defaults:
  - backbone-unet

deep_supervision:
  enabled: true # Training with deep supervision
  levels: 3

fusion: # Fusion strategy for deep supervision and output mode
  mode: "no_fuse_only_final" # Options: 'weighted_softmax', 'weighted_majority', 'no_fuse_only_final'
  weights: [0.1, 0.3, 0.6]
