defaults:
  - backbone-unet

awaken_consistency:
  enabled: true
  num_epoch_awakening: 20

# Note: In backbone-unet, the inference input strategy is always 'single'.
# Deep supervision utilizes 'output_fusion_mode', so do not confuse the two.
# This also employs the strategy pattern.
inference_input_strategy: "single" # Options: 'single', 'multi', 'random'.
