dataset:
  base_path: datasets/
  images_subdir: imagesTr
  labels_subdir: labelsTr
  target_shape:
  - 64
  - 64
  - 64
  task_name: Task04_Hippocampus
gpu:
  backend: nccl
  devices:
  - 1
  mode: single
trained_models:
  base_dir: trained_models
training:
  batch_size: 8
  drop_last: true
  dropout: 0.05
  learning_rate: 0.0001
  n_filters: 16
  num_classes: 4
  num_epochs: 10
  weight_decay: 1.0e-07
