gpu:
  backend: nccl
  devices:
  - 1
  mode: single
trained_models:
  base_dir: trained_models
training:
  batch_size: 2
  dataset_path: datasets/Task08_HepaticVessel/
  dropout: 0.1
  images_subdir: imagesTr
  labels_subdir: labelsTr
  learning_rate: 0.0001
  n_filters: 8
  num_classes: 3
  num_epochs: 1
  weight_decay: 1.0e-07
